=== Jotaela/tallerxml/NF3.2/facturacio.dtd
<!ELEMENT facturacio (empresa, factura+)>
<!ELEMENT empresa (raosocial)>
<!ATTLIST raosocial tipus (empresa | persona) #REQUIRED>
<!ELEMENT raosocial (nom, cognom*, adreca, codipostal, poblacio, (DNI | NIF))>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT adreca (#PCDATA)>
<!ELEMENT codipostal (#PCDATA)>
<!ELEMENT poblacio (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT NIF (#PCDATA)>
<!ATTLIST factura numero CDATA #REQUIRED>
<!ELEMENT factura (client, rebut+, data, subtotal, iva, total)>
<!ELEMENT client (raosocial)>
<!ATTLIST rebut numero CDATA #REQUIRED>
<!ELEMENT rebut (data, totalrebut, linies)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT totalrebut (#PCDATA)>
<!ELEMENT linies (producte+)>
<!ATTLIST producte codi CDATA #REQUIRED>
<!ELEMENT producte (descripcio, quantitat, preuunitari)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT preuunitari (#PCDATA)>
<!ELEMENT subtotal (#PCDATA)>
<!ELEMENT iva (#PCDATA)>
<!ELEMENT total (#PCDATA)>

=== Jotaela/tallerxml/NF3.2/facturacio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturacio SYSTEM "facturacio.dtd">
<facturacio>
    <empresa>
        <raosocial tipus="empresa">
            <nom>DIAGON SA</nom>
            <adreca>Callejon Diagon</adreca>
            <codipostal>17760</codipostal>
            <poblacio>Londres</poblacio>
            <NIF>B17818181NK</NIF>
        </raosocial>
    </empresa>
    
    <factura numero="12">
        <client>
            <raosocial tipus="persona" >
                <nom>Harry</nom>
                <cognom>Potter</cognom>
                <cognom>Evans</cognom>
                <adreca>Privet Drive 4</adreca>
                <codipostal>17600</codipostal>
                <poblacio>Londres</poblacio>
                <DNI>40444444-M</DNI>
            </raosocial>
        </client>
        <rebut numero="23">
            <data>12-10-2010</data>
            <totalrebut>524</totalrebut>
            <linies>
                <producte codi="11115">
                    <descripcio>Caldero de Peltre</descripcio>
                    <quantitat>1</quantitat>
                    <preuunitari>100</preuunitari>
                </producte>
                <producte codi="11112">
                     <descripcio>Tunica de Gryffindor</descripcio>
                     <quantitat>4</quantitat>
                     <preuunitari>106</preuunitari>
                </producte>
            </linies>
        </rebut>
        <rebut numero="28">
            <data>14-10-2010</data>
            <totalrebut>220</totalrebut>
            <linies>
                <producte codi="11111">
                    <descripcio>Nimbus 2000</descripcio>
                    <quantitat>2</quantitat>
                    <preuunitari>110</preuunitari>
                </producte>
            </linies>
        </rebut>
        <data>15-10-2010</data>
        <subtotal>744</subtotal>
        <iva>18</iva>
        <total>877.92</total>        
    </factura>
    
    <factura numero="13">
        <client>
            <raosocial tipus="empresa">
                <nom>Dementores, SA</nom>
                <adreca>c/Del Pac√≠fic, 28</adreca>
                <codipostal>28013</codipostal>
                <poblacio>Azkaban</poblacio>
                <NIF>A88888888</NIF>                
            </raosocial>                     
        </client>
        <rebut numero="24">
            <data>12-10-2010</data>
            <totalrebut>5000</totalrebut>
            <linies>
                <producte codi="11115">
                    <descripcio>Caldero de Peltre</descripcio>
                    <quantitat>50</quantitat>
                    <preuunitari>100</preuunitari>
                </producte>                    
            </linies>
        </rebut>
        <data>15-10-2010</data>
        <subtotal>5000</subtotal>
        <iva>18</iva>
        <total>5900</total>
    </factura>
    
    <factura numero="14">
        <client>
            <raosocial tipus="empresa">              
                <nom>Dervish y Banges, SL</nom>
                <adreca></adreca>
                <codipostal>17600</codipostal>
                <poblacio>Hogsmeade</poblacio>
                <NIF>A177777777</NIF>
            </raosocial>                 
        </client>
        <rebut numero="25">
            <data>13-10-2010</data>
            <totalrebut>110</totalrebut>
            <linies>
                <producte codi="11111">
                    <descripcio>Nimbus 2000</descripcio>
                    <quantitat>1</quantitat>
                    <preuunitari>110</preuunitari>
                </producte>                
            </linies>
        </rebut>
        <rebut numero="26">
            <data>14-10-2010</data>
            <totalrebut>110</totalrebut>
            <linies>
                <producte codi="11111">
                    <descripcio>Nimbus 2000</descripcio>
                    <quantitat>1</quantitat>
                    <preuunitari>110</preuunitari>
                </producte>                
            </linies>
        </rebut>
        <rebut numero="27">
            <data>14-10-2010</data>
            <totalrebut>110</totalrebut>
            <linies>
                <producte codi="11111">
                    <descripcio>Nimbus 2000</descripcio>
                    <quantitat>1</quantitat>
                    <preuunitari>110</preuunitari>
                </producte>                
            </linies>
        </rebut>
        <data>15-10-2010</data>
        <subtotal>330</subtotal>
        <iva>18</iva>
        <total>389.4</total>        
    </factura>    
</facturacio>
